baseURL = 'https://hoangdinhresearchgroup.github.io'
languageCode = 'en-us'
title = 'Hoang Dinh Research Group'
theme = ['mainroad', "hugo-shortcode-gallery"]

[Params.logo]
  image = "img/image.png"


[Params]
  customCSS = ["https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", "css/carousel.css"] # Include custom CSS files
  customJS = ["js/carousel.js"]
  books = "books"

[Params.style.vars]
  highlightColor = "#006699"