baseURL = 'https://hieunch.github.io/lab-website'
languageCode = 'en-us'
title = 'Agile Communications and Computing'
theme = ['mainroad', "hugo-shortcode-gallery"]

[Params.logo]
  image = "img/image.png"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = false  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["recent_news"]

[Params]
  customCSS = ["https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css", "css/carousel.css"] # Include custom CSS files
  customJS = ["js/carousel.js"]
  news = "news"
  books = "books"

[Params.style.vars]
  highlightColor = "#006699"